import type { Metadata } from "next";
import "./globals.css";
import { Navbar, Sidebar } from "@/views";
import { cls } from "hsh-utils-string";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="flex justify-center">
        <div
          className={cls(
            "flex flex-col justify-start items-start",
            "h-screen",
            "shadow-2xl"
          )}
        >
          <Navbar />
          <div className={cls("flex gap-2", "w-[500px]")}>
            <Sidebar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
